# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy
        wget https://github.com/wxtim/pyabc/archive/master.zip -O pyabc.zip
        unzip pyabc.zip -d /home/runner/work/
        pip install -e /home/runner/work/pyabc-master/.
    - name: Pycodestyle
      run: |
        pycodestyle *.py tests/*.py
    - name: Test with pytest
      run: |
        ./etc/tests
